version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file: .env
  db:
    build:
      context: .
    image: postgres:16
    container_name: petstore_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./internal/api/db/migration:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=petstore
