version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: postgres:16
    container_name: petstore_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./internal/api/db/migration:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=petstore
