// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-chi/chi/v5"
	"github.com/jmoiron/sqlx"
	"github.com/rare0b/go-pet-api/internal/api/controller"
	"github.com/rare0b/go-pet-api/internal/api/repository"
	"github.com/rare0b/go-pet-api/internal/api/router"
	"github.com/rare0b/go-pet-api/internal/api/usecase"
)

// Injectors from wire.go:

func Wire(db *sqlx.DB) *chi.Mux {
	petRepository := repository.NewPetRepository(db)
	petUsecase := usecase.NewPetUsecase(db, petRepository)
	petController := controller.NewPetController(petUsecase)
	handler := router.NewPetRouter(petController)
	mux := router.NewMainRouter(handler)
	return mux
}
